[project]
name = "whisper-env"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "moviepy>=1.0.3",
    "imageio-ffmpeg>=0.4.0",
    "yt-dlp @ git+https://github.com/yt-dlp/yt-dlp.git@master",
    "requests>=2.31.0",
]
